import Head from 'next/head'
import dynamic from 'next/dynamic'
import { ErrorBoundary } from 'react-error-boundary'

// Dynamic imports
// const Header = dynamic<{ teste: string }>(() => import('auth/nav'), { ssr: false })
const HeaderPage = dynamic(() => import('auth/pages'), { ssr: false })


// Fallback component for errors
function ErrorFallback({ error, resetErrorBoundary }: { error: Error; resetErrorBoundary: () => void }) {
  return (
    <div role="alert" style={{ color: 'red' }}>
      <p>Something went wrong:</p>
      <pre>{error.message}</pre>
      <button onClick={resetErrorBoundary}>Try again</button>
    </div>
  )
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ErrorBoundary FallbackComponent={ErrorFallback}>
          <HeaderPage /> 
        </ErrorBoundary>
      </main>
    </>
  )
}
